/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as BusinessTechnologyRouteImport } from './routes/business-technology'
import { Route as ChurchPosterDesignRouteImport } from './routes/church-poster-design'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PosInventoryRouteImport } from './routes/pos-inventory'
import { Route as ProfessionalEmailRouteImport } from './routes/professional-email'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as WebDesignRouteImport } from './routes/web-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessTechnologyRoute = BusinessTechnologyRouteImport.update({
  id: '/business-technology',
  path: '/business-technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchPosterDesignRoute = ChurchPosterDesignRouteImport.update({
  id: '/church-poster-design',
  path: '/church-poster-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PosInventoryRoute = PosInventoryRouteImport.update({
  id: '/pos-inventory',
  path: '/pos-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalEmailRoute = ProfessionalEmailRouteImport.update({
  id: '/professional-email',
  path: '/professional-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branding': typeof BrandingRoute
  '/business-technology': typeof BusinessTechnologyRoute
  '/church-poster-design': typeof ChurchPosterDesignRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/pos-inventory': typeof PosInventoryRoute
  '/professional-email': typeof ProfessionalEmailRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branding': typeof BrandingRoute
  '/business-technology': typeof BusinessTechnologyRoute
  '/church-poster-design': typeof ChurchPosterDesignRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/pos-inventory': typeof PosInventoryRoute
  '/professional-email': typeof ProfessionalEmailRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branding': typeof BrandingRoute
  '/business-technology': typeof BusinessTechnologyRoute
  '/church-poster-design': typeof ChurchPosterDesignRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/pos-inventory': typeof PosInventoryRoute
  '/professional-email': typeof ProfessionalEmailRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solutions': typeof SolutionsRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/branding'
    | '/business-technology'
    | '/church-poster-design'
    | '/contact'
    | '/digital-marketing'
    | '/portfolio'
    | '/pos-inventory'
    | '/professional-email'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/web-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/branding'
    | '/business-technology'
    | '/church-poster-design'
    | '/contact'
    | '/digital-marketing'
    | '/portfolio'
    | '/pos-inventory'
    | '/professional-email'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/web-design'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/branding'
    | '/business-technology'
    | '/church-poster-design'
    | '/contact'
    | '/digital-marketing'
    | '/portfolio'
    | '/pos-inventory'
    | '/professional-email'
    | '/services'
    | '/sitemap.xml'
    | '/solutions'
    | '/web-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrandingRoute: typeof BrandingRoute
  BusinessTechnologyRoute: typeof BusinessTechnologyRoute
  ChurchPosterDesignRoute: typeof ChurchPosterDesignRoute
  ContactRoute: typeof ContactRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  PortfolioRoute: typeof PortfolioRoute
  PosInventoryRoute: typeof PosInventoryRoute
  ProfessionalEmailRoute: typeof ProfessionalEmailRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolutionsRoute: typeof SolutionsRoute
  WebDesignRoute: typeof WebDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-technology': {
      id: '/business-technology'
      path: '/business-technology'
      fullPath: '/business-technology'
      preLoaderRoute: typeof BusinessTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church-poster-design': {
      id: '/church-poster-design'
      path: '/church-poster-design'
      fullPath: '/church-poster-design'
      preLoaderRoute: typeof ChurchPosterDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-inventory': {
      id: '/pos-inventory'
      path: '/pos-inventory'
      fullPath: '/pos-inventory'
      preLoaderRoute: typeof PosInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-email': {
      id: '/professional-email'
      path: '/professional-email'
      fullPath: '/professional-email'
      preLoaderRoute: typeof ProfessionalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrandingRoute: BrandingRoute,
  BusinessTechnologyRoute: BusinessTechnologyRoute,
  ChurchPosterDesignRoute: ChurchPosterDesignRoute,
  ContactRoute: ContactRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  PortfolioRoute: PortfolioRoute,
  PosInventoryRoute: PosInventoryRoute,
  ProfessionalEmailRoute: ProfessionalEmailRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolutionsRoute: SolutionsRoute,
  WebDesignRoute: WebDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
